version: "3.2"
services:
  psql:
    container_name: dev-postgres
    image: postgres:10.11
    restart: always
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=
    ports:
      - 7023:5432
